apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-approve
  namespace: kargo-ccs
spec:
  vars:
  - name: repoURL
    value: https://github.com/scott-hpe/kargo-ccs.git
  - name: branch
    value: main
  - name: image
    value: ghcr.io/scott-hpe/guestbook
  - name: cluster
    value: ${{ ctx.stage }}
  steps:

  # Clone the Git repository that contains the Kustomize configuration
  # to the ./src directory, and the environment configuration to ./out.
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom(vars.repoURL).ID }}
        path: ./src
      - branch: env/${{ vars.cluster }}
        path: ./out
        # Create the branch if it does not exist.
        create: true

  # Following a "rendered branch" pattern, we delete all files in the
  # ./out directory to ensure that we only have the files that are
  # rendered from the Kustomize configuration in the ./src directory
  # of the repository after being rendered.
  - uses: git-clear
    config:
      path: ./out

  # Update the image in the Kustomize configuration located at ./src/env/<stage>
  # in the repository.
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/env/${{ vars.cluster }}
      images:
      - image: ${{ vars.image }}
        tag: ${{ imageFrom(vars.image).Tag}}

  # Build the Kustomize configuration in the ./src directory using the env/<stage>
  # overlay to the ./out directory.
  - uses: kustomize-build
    config:
      path: ./src/env/${{ vars.cluster }}
      outPath: ./out

  # Commit the changes to the Git repository.
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-image'].commitMessage }}

  # Push the changes to the Git repository.
  - if: ${{ status('commit') != 'Skipped' }}
    uses: git-push
    as: push
    config:
      path: ./out
      generateTargetBranch: true

  # If new changes were pushed, open a PR for approval
  - if: ${{ status('commit') != 'Skipped' }}
    uses: git-open-pr
    as: open-pr
    config: 
      repoURL: ${{ vars.repoURL }}
      createTargetBranch: true
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: env/${{ vars.cluster }}

  # If new changes were pushed, watch the PR for approval / close
  - if: ${{ status('commit') != 'Skipped' }}
    uses: git-wait-for-pr
    as: wait-for-pr
    config:
      repoURL: ${{ vars.repoURL }}
      prNumber: ${{ task.outputs['open-pr'].pr.id }}

  # Request a sync of the ArgoCD Application to apply the changes from the
  # PR commit. Note that if the PR commit never happened, then it should be
  # from last commit on the environment
  - if: ${{ status('commit') != 'Skipped' }}
    uses: argocd-update
    config:
      apps:
      - name: ccs-guestbook-${{ vars.cluster }}
        sources:
        - repoURL: ${{ vars.repoURL }}
          desiredRevision: ${{ task.outputs['wait-for-pr'].commit }}