apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: green
  name: aquila
  namespace: kargo-ccs
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - pavo-primary
          - pavo-secondary