apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: green
  name: aquila-primary
  namespace: kargo-ccs
spec:
  promotionTemplate:
    spec:
      vars:
        - name: cluster
          value: "aquila-${{ sharedConfigMap('cluster-region-state')[ctx.stage] }}"
      steps:
        - task:
            name: promote-approve
  requestedFreight:
    - origin:
        kind: Warehouse
        name: ccs-guestbook
      sources:
        requiredSoakTime: 30m0s
        stages:
          - pavo-primary