apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: blue
  name: pavo
  namespace: kargo-ccs
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: ccs-guestbook
      sources:
        stages:
          - mira-primary
          - mira-secondary