apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: green
  name: aquila-primary
  namespace: kargo-ccs
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-approve
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - aquila