apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ccs-guestbook
  namespace: kargo-ccs
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/scott-hpe/guestbook
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
  - git:
      repoURL: https://github.com/scott-hpe/kargo-ccs.git
      branch: main
      includePaths:
        - base/
        - env/
